---
abstract: 'An interface to the WordPress XML-RPC API'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  Test::Fatal: 0
  Test::More: 0.88
  lib: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WP-API
requires:
  Carp: 0
  DateTime: 0
  Moose: 0
  MooseX::Params::Validate: 0
  MooseX::Role::Parameterized: 0
  MooseX::StrictConstructor: 0
  MooseX::Types::Combine: 0
  MooseX::Types::Common::String: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::URI: 0
  Scalar::Util: 0
  XMLRPC::Lite: 0
  namespace::autoclean: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=WP-API
  homepage: http://metacpan.org/release/WP-API
  repository: git://git.urth.org/WP-API.git
version: 0.01
x_authority: cpan:DROLSKY
